matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake-data
            - cmake
            - libslicot-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - make test