matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:octave/stable'
          packages:
            - g++-4.9
            - cmake-data
            - cmake
            - libslicot-dev
            - octave
            - liboctave-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          taps: nlesc/nlesc
          packages:
            - ccache
          update: true
      before_install:
         - brew install nlesc/nlesc/slicot

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - make check
